# Use an officia Node.js runtime as a parent image
FROM node:18-alpine

# Set the working directory in the container
WORKDIR /usr/src/app

# COpy package.json and package-lock.json to the working diretory
COPY package*.json ./

# Install app dependencies
RUN npm install

# Copy the rest of the application code to the working directory
COPY . .

CMD ["npm", "start"]

EXPOSE 3000